language: node_js
node_js:
- 7
script:
- npm run test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
#Deploy build to Github pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
